name: dhook
description: >-
  A lightweight webhook relay service to forward webhooks from cloud to your 
  local development environment in real-time. Alternative to smee.io with 
  self-hosted server support.
version: 1.0.8
repository: https://github.com/alisheraxmedov/dhook
homepage: https://github.com/alisheraxmedov/dhook
issue_tracker: https://github.com/alisheraxmedov/dhook/issues
topics:
  - webhook
  - cli
  - development
  - relay
  - proxy

environment:
  sdk: ^3.9.2

executables:
  dhook: dhook

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  http: ^1.6.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.2
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  stream_channel: ^2.1.4
  test: ^1.25.6
