name: dhook
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.0
  http: ^1.6.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.2
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
